# Example configuration for config/credentials.yml.enc
# Use: EDITOR="code --wait" rails credentials:edit

# External API Keys for importing listings
# Uncomment and add your actual API keys:

# tripadvisor:
#   api_key: your_tripadvisor_api_key_here

# google:
#   places_api_key: your_google_places_api_key_here

# foursquare:
#   api_key: your_foursquare_api_key_here

# How to get API keys:
#
# TripAdvisor API:
# 1. Visit: https://developer-tripadvisor.com/
# 2. Create an account and request access
# 3. Add the API key to credentials under tripadvisor.api_key
#
# Google Places API:
# 1. Visit: https://console.cloud.google.com/
# 2. Enable the Places API
# 3. Create a API key with Places API permissions
# 4. Add the API key to credentials under google.places_api_key
#
# Foursquare API:
# 1. Visit: https://developer.foursquare.com/
# 2. Create an app and get your API key
# 3. Add the API key to credentials under foursquare.api_key
